CREATE TABLE area
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    active      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_area PRIMARY KEY (id)
);

CREATE TABLE destination_inform
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    state               VARCHAR(255),
    reception_date      TIMESTAMP WITHOUT TIME ZONE,
    date_reading        TIMESTAMP WITHOUT TIME ZONE,
    inform_id           BIGINT,
    area_destination_id BIGINT,
    user_destination    BIGINT,
    CONSTRAINT pk_destination_inform PRIMARY KEY (id)
);

CREATE TABLE employee
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name              VARCHAR(255)                            NOT NULL,
    last_name               VARCHAR(255)                            NOT NULL,
    phone                   BIGINT                                  NOT NULL,
    identifier              BIGINT                                  NOT NULL,
    username                VARCHAR(255)                            NOT NULL,
    institutional_email     VARCHAR(255)                            NOT NULL,
    password                VARCHAR(255)                            NOT NULL,
    enabled                 BOOLEAN,
    account_non_expired     BOOLEAN,
    account_non_locked      BOOLEAN,
    credentials_non_expired BOOLEAN,
    area_id                 BIGINT                                  NOT NULL,
    CONSTRAINT pk_employee PRIMARY KEY (id)
);

CREATE TABLE employee_roles
(
    employee_id BIGINT NOT NULL,
    role_id     BIGINT NOT NULL,
    CONSTRAINT pk_employee_roles PRIMARY KEY (employee_id, role_id)
);

CREATE TABLE history_changes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    object_name VARCHAR(255),
    operation   VARCHAR(255),
    username    VARCHAR(255),
    date        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_history_changes PRIMARY KEY (id)
);

CREATE TABLE history_states
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    inform_id     BIGINT,
    request_id    BIGINT,
    state         VARCHAR(255),
    request_state VARCHAR(255),
    user_id       BIGINT,
    date          TIMESTAMP WITHOUT TIME ZONE,
    description   VARCHAR(255),
    CONSTRAINT pk_history_states PRIMARY KEY (id)
);

CREATE TABLE inform
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         VARCHAR(255),
    description   VARCHAR(255),
    status        VARCHAR(255),
    creation_date TIMESTAMP WITHOUT TIME ZONE,
    user_id       BIGINT,
    area_id       BIGINT,
    CONSTRAINT pk_inform PRIMARY KEY (id)
);

CREATE TABLE permissions
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

CREATE TABLE request
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              VARCHAR(255)                            NOT NULL,
    description        VARCHAR(2000)                           NOT NULL,
    state              VARCHAR(255)                            NOT NULL,
    solicitante_id     BIGINT                                  NOT NULL,
    area_destino_id    BIGINT,
    usuario_destino_id BIGINT,
    creation_date      TIMESTAMP WITHOUT TIME ZONE,
    response_date      TIMESTAMP WITHOUT TIME ZONE,
    response           VARCHAR(2000),
    CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE role_permissions
(
    permission_id BIGINT NOT NULL,
    role_id       BIGINT NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (permission_id, role_id)
);

CREATE TABLE roles
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

ALTER TABLE employee
    ADD CONSTRAINT uc_employee_identifier UNIQUE (identifier);

ALTER TABLE employee
    ADD CONSTRAINT uc_employee_username UNIQUE (username);

ALTER TABLE destination_inform
    ADD CONSTRAINT FK_DESTINATION_INFORM_ON_AREA_DESTINATION FOREIGN KEY (area_destination_id) REFERENCES area (id);

ALTER TABLE destination_inform
    ADD CONSTRAINT FK_DESTINATION_INFORM_ON_INFORM FOREIGN KEY (inform_id) REFERENCES inform (id);

ALTER TABLE destination_inform
    ADD CONSTRAINT FK_DESTINATION_INFORM_ON_USER_DESTINATION FOREIGN KEY (user_destination) REFERENCES employee (id);

ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_AREA FOREIGN KEY (area_id) REFERENCES area (id);

ALTER TABLE inform
    ADD CONSTRAINT FK_INFORM_ON_AREA FOREIGN KEY (area_id) REFERENCES area (id);

ALTER TABLE inform
    ADD CONSTRAINT FK_INFORM_ON_USER FOREIGN KEY (user_id) REFERENCES employee (id);

ALTER TABLE request
    ADD CONSTRAINT FK_REQUEST_ON_AREA_DESTINO FOREIGN KEY (area_destino_id) REFERENCES area (id);

ALTER TABLE request
    ADD CONSTRAINT FK_REQUEST_ON_SOLICITANTE FOREIGN KEY (solicitante_id) REFERENCES employee (id);

ALTER TABLE request
    ADD CONSTRAINT FK_REQUEST_ON_USUARIO_DESTINO FOREIGN KEY (usuario_destino_id) REFERENCES employee (id);

ALTER TABLE employee_roles
    ADD CONSTRAINT fk_emprol_on_role_entity FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE employee_roles
    ADD CONSTRAINT fk_emprol_on_user_entity FOREIGN KEY (employee_id) REFERENCES employee (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_rolper_on_permission_entity FOREIGN KEY (permission_id) REFERENCES permissions (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_rolper_on_role_entity FOREIGN KEY (role_id) REFERENCES roles (id);